<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-PUJJMK1" failures="1" tests="1" name="Default test(failed)(failed)(failed)" time="0.004" errors="0" timestamp="27 Feb 2024 10:24:07 GMT">
  <testcase classname="com.scenario.automate.RunOnlyFailedTests" name="anotherFailure" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at com.scenario.automate.RunOnlyFailedTests.anotherFailure(RunOnlyFailedTests.java:22)
	at com.scenario.automate.utils.RunFailedOnly.runTestLoader(RunFailedOnly.java:55)
	at com.scenario.automate.RunOnlyFailedTests.testRunOnlyTest(RunOnlyFailedTests.java:28)
... Removed 50 stack frames]]>
    </failure>
  </testcase> <!-- anotherFailure -->
</testsuite> <!-- Default test(failed)(failed)(failed) -->
